name: eventpro
description: EasyPass est une plateforme d'achat de billet d'access a tout type de manifestation social ou culturelle mais egalement professionnel.Il est rettacher a un systeme de control anti-fraude robuste.
publish_to: "none"
version: 3.2.6

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  ticket_widget: ^0.0.1
  flutter_spinbox: ^0.13.0
  cupertino_icons: ^1.0.2
  responsive_framework: ^1.1.0
  google_fonts: ^6.1.0
  animations: ^2.0.0
  pin_code_text_field: ^1.8.0
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^2.0.4
  intl: ^0.18.1
  simple_gesture_detector: ^0.2.0
  # modal_bottom_sheet: ^2.0.0
  url_launcher: ^6.0.9
  fluttertoast: ^8.0.8
  introduction_screen: ^3.0.2
  qr_flutter: ^4.0.0
  rive: ^0.11.4
  get: ^4.6.5
  map_launcher: ^2.4.0
  firebase_auth: ^4.10.0
  google_sign_in: ^6.0.2
  # firebase_core: ^2.8.0
  firebase_core: ^2.4.0
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.2
  flutter_easyloading: ^3.0.5
  intl_phone_field: ^3.1.0
  floating_bottom_navigation_bar: ^1.5.2
  ticket_material: ^0.3.1
  fancy_shimmer_image: ^2.0.2
  country_icons: ^2.0.2
  gif_view: ^0.4.0
  firebase_database: ^10.0.2
  avatar_glow: ^2.0.2
  screen_protector: ^1.1.3+1
  firebase_messaging: ^14.0.2
  flutter_local_notifications: ^15.1.0+1
  add_2_calendar: ^2.1.2
  story_view: ^0.15.0
  flutter_launcher_icons: ^0.13.1
  simple_connection_checker: ^0.2.1
  media_picker_widget: ^1.0.4
  random_avatar: ^0.0.7
  flutter_inappwebview: ^5.7.1
  status_view: ^0.0.2
  shared_preferences: ^2.0.15
  platform_device_id: ^1.0.1
  package_info_plus: ^4.1.0
  #firebase_app_check: ^0.1.2
  firebase_in_app_messaging: ^0.7.0+7
  ntp: ^2.0.0
  new_version_plus: ^0.0.9
  internet_connection_checker: ^1.0.0+1
  fast_contacts: ^3.0.3
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  # nfc_manager: ^3.2.0
  permission_handler: ^11.0.0
  firebase_dynamic_links: ^5.0.17
  beamer: ^1.5.3
  firebase_auth_web: ^5.2.10
  share_plus: ^7.1.0
  get_storage: ^2.1.1
  responsive_builder: ^0.7.0
  flutter_web_frame: ^1.0.0
  flutter_barcode_scanner: ^2.0.0
  cart_stepper: ^4.1.2
  uni_links: ^0.5.1
  zego_uikit_prebuilt_live_streaming: ^2.22.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpeg"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.jpeg"
    background_color: "#ffff"
    theme_color: "#ffff"
flutter:
  uses-material-design: true
  assets:
    - assets/
